const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
  connectionTimeout: 30000,
  greetingTimeout: 30000,
  socketTimeout: 30000,
});

function markdownToHtml(text) {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^### (.+)$/gm, '<h3 style="color:#1a1a2e;font-size:16px;margin:18px 0 8px;font-weight:700;">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 style="color:#1a1a2e;font-size:18px;margin:22px 0 10px;font-weight:700;">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 style="color:#1a1a2e;font-size:20px;margin:24px 0 12px;font-weight:700;">$1</h1>')
    .replace(/^- (.+)$/gm, '<li style="color:#444;margin:4px 0;line-height:1.6;">$1</li>')
    .replace(/^(\d+)\. (.+)$/gm, '<li style="color:#444;margin:4px 0;line-height:1.6;">$2</li>')
    .replace(/(<li.*<\/li>\n?)+/g, '<ul style="padding-left:20px;margin:8px 0;">$&</ul>')
    .replace(/\n\n/g, '</p><p style="color:#333;line-height:1.8;margin:12px 0;">')
    .replace(/\n/g, '<br>');
}

async function sendSummaryEmail(to, summary) {
  const formattedSummary = markdownToHtml(summary);

  const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background:#f0f0f5;font-family:'Segoe UI',Roboto,Arial,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:40px 20px;">

    <!-- Header -->
    <div style="text-align:center;margin-bottom:32px;">
      <div style="display:inline-block;background:linear-gradient(135deg,#6C63FF,#7c5ce7);padding:14px 28px;border-radius:12px;margin-bottom:16px;">
        <span style="color:#ffffff;font-size:24px;font-weight:800;letter-spacing:-0.5px;">Rabbitt AI</span>
      </div>
      <p style="color:#64748b;font-size:13px;margin:0;font-weight:500;letter-spacing:0.5px;">SALES INSIGHT AUTOMATOR</p>
    </div>

    <!-- Main Card -->
    <div style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

      <!-- Purple Bar -->
      <div style="height:4px;background:linear-gradient(90deg,#6C63FF,#a78bfa,#6C63FF);"></div>

      <!-- Content -->
      <div style="padding:36px 32px;">
        <h2 style="color:#1a1a2e;font-size:20px;margin:0 0 6px;font-weight:700;">Your AI-Generated Summary</h2>
        <p style="color:#94a3b8;font-size:13px;margin:0 0 24px;font-weight:400;">Here is the analysis of your uploaded data</p>

        <div style="border-top:1px solid #f1f5f9;padding-top:24px;">
          <p style="color:#333;line-height:1.8;margin:12px 0;">${formattedSummary}</p>
        </div>
      </div>

      <!-- Divider -->
      <div style="height:1px;background:#f1f5f9;margin:0 32px;"></div>

      <!-- Footer inside card -->
      <div style="padding:20px 32px;text-align:center;">
        <p style="color:#94a3b8;font-size:12px;margin:0;">This summary was auto-generated by AI. Please verify key figures independently.</p>
      </div>
    </div>

    <!-- Footer -->
    <div style="text-align:center;margin-top:28px;">
      <p style="color:#94a3b8;font-size:11px;margin:0;">Powered by <span style="color:#6C63FF;font-weight:600;">Rabbitt AI</span> &mdash; Sales Insight Automator</p>
    </div>

  </div>
</body>
</html>`;

  await transporter.sendMail({
    from: '"Rabbitt AI" <' + process.env.GMAIL_USER + '>',
    to,
    subject: 'Your AI Data Summary — Rabbitt AI',
    html: htmlBody,
  });
}

module.exports = { sendSummaryEmail };
