const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

async function sendSummaryEmail(to, summary) {
  const htmlBody = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #f9f9fb; padding: 30px; border-radius: 12px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #6C63FF; margin: 0; font-size: 28px;">Rabbitt AI</h1>
        <p style="color: #888; margin: 4px 0 0;">Sales Insight Automator</p>
      </div>
      <div style="background: #ffffff; padding: 24px; border-radius: 8px; border: 1px solid #e8e8ec;">
        <h2 style="color: #1a1a2e; font-size: 18px; margin-top: 0;">Your AI-Generated Summary</h2>
        <div style="color: #333; line-height: 1.7; white-space: pre-wrap;">${summary}</div>
      </div>
      <p style="text-align: center; color: #aaa; font-size: 12px; margin-top: 24px;">
        Generated by Rabbitt AI — Sales Insight Automator
      </p>
    </div>
  `;

  await transporter.sendMail({
    from: '"Rabbitt AI" <' + process.env.GMAIL_USER + '>',
    to,
    subject: 'Your AI Data Summary — Rabbitt AI',
    html: htmlBody,
  });
}

module.exports = { sendSummaryEmail };
